# Generated by Django 4.2.6 on 2023-11-15 06:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_alter_article_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='CommentModel',
        ),
    ]
