# Generated by Django 4.2.6 on 2023-11-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_project_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'پیام', 'verbose_name_plural': 'پیام ها'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'پروژه', 'verbose_name_plural': 'پروژه ها'},
        ),
        migrations.AlterModelOptions(
            name='projectcategories',
            options={'verbose_name': 'دسته بندی پروژه', 'verbose_name_plural': 'دسته بندی های پروژه'},
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(verbose_name='بدنه'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='ایجاد شده'),
        ),
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=57, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(max_length=107, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='project',
            name='about_customer',
            field=models.TextField(verbose_name='درباره مشتری'),
        ),
        migrations.AlterField(
            model_name='project',
            name='body',
            field=models.TextField(verbose_name='بدنه'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ManyToManyField(related_name='projects', to='home.projectcategories', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده'),
        ),
        migrations.AlterField(
            model_name='project',
            name='customer',
            field=models.CharField(max_length=50, verbose_name='مشتری'),
        ),
        migrations.AlterField(
            model_name='project',
            name='extra_details',
            field=models.TextField(verbose_name='جزئیات بیشتر'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='projects/images', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image2',
            field=models.ImageField(upload_to='projects/images', verbose_name='عکس 2'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image3',
            field=models.ImageField(upload_to='projects/images', verbose_name='عکس 3'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image4',
            field=models.ImageField(upload_to='projects/images', verbose_name='عکس 4'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image5',
            field=models.ImageField(upload_to='projects/images', verbose_name='عکس 5'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image6',
            field=models.ImageField(upload_to='projects/images', verbose_name='عکس 6'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image7',
            field=models.ImageField(upload_to='projects/images', verbose_name='عکس 7'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.BooleanField(default=True, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=50, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='به روز شده'),
        ),
        migrations.AlterField(
            model_name='projectcategories',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده'),
        ),
        migrations.AlterField(
            model_name='projectcategories',
            name='title',
            field=models.CharField(max_length=50, verbose_name='عنوان'),
        ),
    ]
